language: bash
jobs:
  include:
    - stage: build
      before_script:
      - bash -c "echo before_script"
      script:
      - echo script
      - echo script 2
      if: tag IS blank AND type = pull_request
    - stage: push image
      if: type = push AND branch = main
      before_deploy:
        provider: script
        script: bash ./scripts/run-ci.sh before_deploy
      deploy:
        provider: script 
        script: bash ./scripts/run-ci.sh deploy
        on:
          branch: main
    - stage: push release to dokcerhub
      if: tag IS present
      before_deploy:
        provider: script
        script: bash ./scripts/run-ci.sh before_tag_deploy
      deploy: 
        provider: script
        script: bash ./scripts/run-ci.sh tag_deploy
        on:
          tags: true
          all_branches: true
        condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
